services:
  web:
    image: seletivo-numera:latest
    build: .
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app


  mongo:
    image: mongo:latest
    env_file: 
      - .env
    ports:
      - "${MONGO_PORT:-27017}:27017"