name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set execute permission for entrypoint.sh
      run: chmod +x entrypoint.sh

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: my-image-name:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create .env file
      run: |
        echo "MONGO_IP=${{ secrets.MONGO_IP }}" >> .env
        echo "MONGODB_PORT_NUMBER=${{ secrets.MONGO_PORT }}" >> .env
        echo "MONGO_DBNAME=${{ secrets.MONGO_DBNAME }}" >> .env
        echo "MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }}" >> .env
        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USER }}" >> .env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}" >> .env
        echo "MONGO_USER=${{ secrets.MONGO_ROOT_PASSWORD }}" >> .env
        echo "MONGO_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}" >> .env
        echo "FLASK_APP=${{ secrets.FLASK_APP }}" >> .env
        echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> .env
        echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> .env

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Verify Docker Compose
      run: docker-compose ps

    - name: Clean up .env file
      run: rm .env
